import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { jsPDF } from 'jspdf';
import { ApiService } from '../api.service';

@Component({
  selector: 'app-reports-page',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="reports">
      <header class="report-header">
        <div>
          <p class="eyebrow">Business Intelligence</p>
          <h1><span class="material-symbols-outlined">insights</span> Report Studio</h1>
          <p>Generate datasets, save snapshots, and export in JSON, CSV, or PDF.</p>
        </div>
        <div class="header-actions">
          <button class="btn-base btn-primary" (click)="generate()">Generate</button>
          <button class="btn-base btn-secondary" (click)="saveSnapshot()" [disabled]="!reportRows().length">Save Snapshot</button>
          <button class="btn-base btn-secondary" (click)="exportJson()" [disabled]="!reportRows().length">JSON</button>
          <button class="btn-base btn-secondary" (click)="exportCsv()" [disabled]="!reportRows().length">CSV</button>
          <button class="btn-base btn-secondary" (click)="exportPdf()" [disabled]="!reportRows().length">PDF</button>
        </div>
      </header>

      <div class="grid top-grid">
        <article class="panel controls">
          <h2>Report Controls</h2>
          <div class="control-grid">
            <div>
              <label>Dataset</label>
              <select class="app-select" [(ngModel)]="selectedDataset">
                <option *ngFor="let ds of datasets" [value]="ds.path">{{ ds.label }}</option>
              </select>
            </div>
            <div>
              <label>Report Type (Key)</label>
              <select class="app-select" [(ngModel)]="reportKey">
                <option *ngFor="let key of reportKeyOptions" [value]="key.value">{{ key.label }}</option>
              </select>
            </div>
            <div>
              <label>Title</label>
              <select class="app-select" [(ngModel)]="reportTitle">
                <option *ngFor="let title of reportTitleOptions" [value]="title">{{ title }}</option>
              </select>
            </div>
            <div>
              <label>Generated By User ID</label>
              <input class="app-input" type="number" [(ngModel)]="generatedByUserId" />
            </div>
          </div>
        </article>

        <article class="panel metrics-panel" *ngIf="metrics() as m">
          <h2>Report Metrics</h2>
          <div class="metrics">
            <div class="metric-card m1">
              <p class="label">Rows</p>
              <p class="value">{{ m.rowCount }}</p>
            </div>
            <div class="metric-card m2">
              <p class="label">Numeric Total</p>
              <p class="value">{{ m.numericTotal | number:'1.0-2' }}</p>
            </div>
            <div class="metric-card m3">
              <p class="label">Generated At</p>
              <p class="value">{{ m.generatedAt | date:'medium' }}</p>
            </div>
          </div>
        </article>
      </div>

      <article class="panel data-panel">
        <h2>Report Preview</h2>
        <div class="table-wrap">
          <table *ngIf="reportRows().length; else noReportRows">
            <thead>
              <tr>
                <th>#</th>
                <th *ngFor="let col of reportColumns()">{{ col }}</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let row of reportRows(); let i = index">
                <td class="row-index">{{ i + 1 }}</td>
                <td *ngFor="let col of reportColumns()">{{ toDisplay(row[col]) }}</td>
              </tr>
            </tbody>
          </table>
          <ng-template #noReportRows>
            <p class="empty">No report data loaded yet.</p>
          </ng-template>
        </div>
      </article>

      <p class="status" *ngIf="status()">{{ status() }}</p>
    </section>
  `,
  styles: `
    .reports {
      display: grid;
      gap: 0.8rem;
      height: 100%;
      min-height: 0;
      grid-template-rows: auto auto 1fr auto;
    }
    .report-header {
      border: 1px solid #d9e4f1;
      border-radius: 1rem;
      padding: 0.85rem;
      background: linear-gradient(150deg, #ffffff, #f4f9ff);
      display: flex;
      justify-content: space-between;
      gap: 0.8rem;
      align-items: flex-start;
    }
    .eyebrow { margin: 0; text-transform: uppercase; letter-spacing: 0.09em; font-size: 0.72rem; color: #0f4c5c; font-weight: 700; }
    .report-header h1 { margin: 0.2rem 0; display: flex; align-items: center; gap: 0.35rem; font-size: 1.2rem; }
    .report-header p { margin: 0; color: #5f6f82; font-size: 0.9rem; }
    .header-actions { display: flex; gap: 0.4rem; flex-wrap: wrap; justify-content: flex-end; }

    .grid { display: grid; gap: 0.8rem; min-height: 0; }
    .top-grid { grid-template-columns: 1.2fr 1fr; }

    .panel {
      border: 1px solid #dce6f2;
      border-radius: 1rem;
      padding: 0.75rem;
      background: #fff;
      min-height: 0;
      overflow: hidden;
      display: grid;
      grid-template-rows: auto 1fr;
      gap: 0.55rem;
    }
    .panel h2 { margin: 0; font-size: 1rem; color: #14334f; }

    .controls { background: linear-gradient(165deg, #ffffff, #f5fbff); }
    .metrics-panel { background: linear-gradient(165deg, #ffffff, #f8fff7); }

    .control-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 0.55rem;
      align-items: end;
    }
    label { display: block; font-weight: 700; margin: 0 0 0.25rem; font-size: 0.82rem; color: #43576d; }

    .metrics { display: grid; grid-template-columns: 1fr; gap: 0.5rem; }
    .metric-card {
      border: 1px solid #e4edf8;
      border-radius: 0.75rem;
      padding: 0.55rem;
      background: #fff;
    }
    .m1 { border-left: 5px solid #0f4c5c; }
    .m2 { border-left: 5px solid #2f8c88; }
    .m3 { border-left: 5px solid #f4a261; }
    .label { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.09em; color: #607287; margin: 0; }
    .value { font-size: 0.95rem; color: #102542; margin: 0.2rem 0 0; font-weight: 700; }

    .data-panel {
      background: linear-gradient(165deg, #ffffff, #f3f8ff);
      min-height: 0;
    }
    .table-wrap {
      min-height: 0;
      overflow: auto;
      border: 1px solid #dfeaf6;
      border-radius: 0.7rem;
      background: #fff;
    }
    table { width: 100%; border-collapse: collapse; font-size: 0.8rem; }
    th, td { text-align: left; padding: 0.45rem 0.5rem; border-bottom: 1px solid #edf1f6; vertical-align: top; }
    th {
      position: sticky;
      top: 0;
      background: #0f4c5c;
      color: #ffffff;
      font-weight: 700;
    }
    tbody tr:nth-child(even) { background: #f7fbff; }
    tbody tr:hover { background: #eef6ff; }
    .row-index {
      width: 42px;
      font-weight: 700;
      color: #0f4c5c;
      text-align: center;
      background: #eef6ff;
    }
    .empty { margin: 0; color: #6d8096; padding: 0.8rem; }
    .status { margin: 0; background: #eff9f8; color: #0f4c5c; border: 1px solid #b8e1d9; border-radius: 0.7rem; padding: 0.45rem 0.7rem; font-size: 0.86rem; }

    @media (max-width: 1200px) {
      .reports { height: auto; grid-template-rows: auto; }
      .top-grid { grid-template-columns: 1fr; }
      .control-grid { grid-template-columns: 1fr; }
    }
    @media (max-width: 760px) {
      .report-header { flex-direction: column; }
      .header-actions { justify-content: flex-start; }
      .metrics { grid-template-columns: 1fr; }
    }
  `
})
export class ReportsPageComponent {
  private readonly api = inject(ApiService);

  readonly datasets = [
    { label: 'Accounts', path: '/api/Accounts' },
    { label: 'Products', path: '/api/Product' },
    { label: 'Companies', path: '/api/Company' },
    { label: 'Customers', path: '/api/Customer' },
    { label: 'Reservations', path: '/api/Reservation' },
    { label: 'Invoices', path: '/api/invoices' }
  ];

  readonly reportKeyOptions = [
    { value: 'operations-overview', label: 'Operations Overview' },
    { value: 'accounts-summary', label: 'Accounts Summary' },
    { value: 'sales-products', label: 'Sales & Products' },
    { value: 'customer-activity', label: 'Customer Activity' },
    { value: 'reservation-utilization', label: 'Reservation Utilization' },
    { value: 'invoice-financials', label: 'Invoice Financials' }
  ];

  readonly reportTitleOptions = [
    'Operations Daily Summary',
    'User Accounts and Access Matrix',
    'Product Performance and Pricing',
    'Customer Portfolio Analysis',
    'Reservation Pipeline Report',
    'Invoice and Revenue Snapshot'
  ];

  selectedDataset = '/api/Accounts';
  reportKey = 'operations-overview';
  reportTitle = 'Operations Daily Summary';
  generatedByUserId = 1;

  readonly reportRows = signal<any[]>([]);
  readonly status = signal('');
  readonly metrics = signal<{ rowCount: number; numericTotal: number; generatedAt: string } | null>(null);

  generate(): void {
    this.api.list(this.selectedDataset).subscribe({
      next: (rows) => {
        this.reportRows.set(rows);
        this.metrics.set({
          rowCount: rows.length,
          numericTotal: this.calculateNumericTotal(rows),
          generatedAt: new Date().toISOString()
        });
        this.status.set(`Loaded ${rows.length} rows from ${this.selectedDataset}.`);
      },
      error: (err) => this.status.set(this.describeError(err))
    });
  }

  saveSnapshot(): void {
    const payload = {
      reportKey: this.reportKey,
      title: this.reportTitle,
      dataJson: JSON.stringify(this.reportRows(), null, 2),
      snapshotDate: new Date().toISOString(),
      generatedByUserId: Number(this.generatedByUserId)
    };

    this.api.post('/api/ReportSnapshots', payload).subscribe({
      next: () => this.status.set('Snapshot saved successfully.'),
      error: (err) => this.status.set(this.describeError(err))
    });
  }

  exportJson(): void {
    this.downloadFile(`${this.reportKey}.json`, 'application/json', JSON.stringify(this.reportRows(), null, 2));
  }

  exportCsv(): void {
    const rows = this.reportRows();
    if (!rows.length) {
      return;
    }

    const headers = Object.keys(rows[0]);
    const lines = [headers.join(',')];
    rows.forEach((row) => {
      const values = headers.map((h) => this.escapeCsv(row[h]));
      lines.push(values.join(','));
    });

    this.downloadFile(`${this.reportKey}.csv`, 'text/csv', lines.join('\n'));
  }

  exportPdf(): void {
    const rows = this.reportRows();
    if (!rows.length) {
      return;
    }

    const doc = new jsPDF();
    const columns = Object.keys(rows[0]).slice(0, 8);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 10;
    const tableWidth = pageWidth - margin * 2;
    const colWidth = tableWidth / Math.max(columns.length, 1);
    const rowHeight = 7;

    doc.setFillColor(18, 46, 83);
    doc.rect(0, 0, pageWidth, 24, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(13);
    doc.text(this.reportTitle || 'Report', 10, 10);
    doc.setFontSize(9);
    doc.text(`Key: ${this.reportKey}`, 10, 16);
    doc.text(`Generated: ${new Date().toISOString()}`, 10, 21);

    let y = 30;
    const drawHeader = () => {
      doc.setFillColor(15, 118, 138);
      doc.setTextColor(255, 255, 255);
      columns.forEach((col, index) => {
        const x = margin + index * colWidth;
        doc.rect(x, y, colWidth, rowHeight, 'F');
        const title = col.length > 16 ? `${col.slice(0, 16)}...` : col;
        doc.text(title, x + 1.5, y + 4.8);
      });
      y += rowHeight;
    };

    drawHeader();
    doc.setTextColor(20, 36, 54);
    rows.forEach((row, rowIndex) => {
      if (y + rowHeight > pageHeight - margin) {
        doc.addPage();
        y = margin;
        drawHeader();
        doc.setTextColor(20, 36, 54);
      }

      const rowFill = rowIndex % 2 === 0 ? [239, 248, 251] : [255, 255, 255];
      columns.forEach((col, colIndex) => {
        const x = margin + colIndex * colWidth;
        doc.setFillColor(rowFill[0], rowFill[1], rowFill[2]);
        doc.rect(x, y, colWidth, rowHeight, 'F');
        doc.setDrawColor(210, 224, 236);
        doc.rect(x, y, colWidth, rowHeight, 'S');
        const raw = this.toDisplay(row[col]);
        const value = raw.length > 18 ? `${raw.slice(0, 18)}...` : raw;
        doc.text(value, x + 1.5, y + 4.8);
      });

      y += rowHeight;
    });

    doc.save(`${this.reportKey || 'report'}.pdf`);
  }

  reportColumns(): string[] {
    const first = this.reportRows()[0];
    return first ? Object.keys(first).slice(0, 10) : [];
  }

  toDisplay(value: unknown): string {
    if (value === null || value === undefined || value === '') {
      return '-';
    }
    if (typeof value === 'object') {
      return JSON.stringify(value);
    }
    return String(value);
  }

  private escapeCsv(value: unknown): string {
    if (value === null || value === undefined) {
      return '';
    }

    const text = String(value).replace(/"/g, '""');
    return `"${text}"`;
  }

  private calculateNumericTotal(rows: any[]): number {
    let total = 0;
    rows.forEach((row) => {
      Object.values(row).forEach((value) => {
        if (typeof value === 'number' && Number.isFinite(value)) {
          total += value;
        }
      });
    });

    return total;
  }

  private downloadFile(fileName: string, mimeType: string, content: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    URL.revokeObjectURL(url);
  }

  private describeError(err: any): string {
    const fromApi = err?.error?.message ?? err?.error?.title ?? err?.message;
    return fromApi ? `Request failed: ${fromApi}` : 'Request failed';
  }
}
